version: "3.8"
services:
  mysql:
    image: mysql:latest
    container_name: Database_Container
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: expenses_tracker
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - nw
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: always

  java_app:
    #image: snehcreate/expensetracker_v3
    build:
      context: .
    container_name: Expensetracker_Container
    environment:
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/expenses_tracker?allowPublicKeyRetrieval=true&useSSL=false"
      SPRING_DATASOURCE_PASSWORD: Test@123
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - "8080:8080"
    networks:
      - nw
    depends_on:
      - mysql
    restart: always

networks:
  nw:

# volumes:
#   mysql-data:
